#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
echo "Welcome to RTL8730ELH"

cat /etc/motd

#set country to Worldwide
#iw reg set WW

#enable udhcpd when start hostapd automatically
#if [ -e /var/run/hostapd/wlan1 ]; then
#    ifconfig wlan1 192.168.43.1
#    udhcpd -S /etc/udhcpd.conf
#fi

exit 0
