#!/bin/sh
echo "Welcome to RTL8730ELH Recovery"

mkdir -p /rom/mnt
mkdir -p /proc
mkdir -p /tmp
mkdir -p /sys
mkdir -p /mnt

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp

if [ -e /dev/ubi0_0 ]; then
    mount -t ubifs ubi0_0 /rom/mnt
else
    mount -t jffs2 /dev/mtdblock5 /rom/mnt
fi

mkdir -p /var/run

cat /etc/motd
echo /sbin/mdev > /proc/sys/kernel/hotplug

update_mode=$(/usr/bin/fw_printenv -n update_mode)

if [ "x$update_mode" = "xnormal" ] &&  [ -e /bin/recovery ]; then
    recovery > /dev/ttyS0
elif [ -e /bin/recovery.sh ]; then
    ./bin/recovery.sh > /dev/ttyS0
fi

reboot

