#!/usr/bin/env python
import sys
import time

dtb_label = "Device Tree Blob"
kernel_label = "Kernel Image"
rootfs_label = "Rootfs Image"
reg_chara = "reg = <"

def get_size(file_name, label):
    with open(file_name, 'r') as file:
        find_label = None
        for line in file:
            if find_label is None:
                # Ignoring uppercase and lowercase letters
                if label.lower() in line.lower():
                    find_label = 1
            else:
                if reg_chara in line:
                    lst_temp1 = line.split("<")
                    lst_temp2 = lst_temp1[1].split(">")
                    lst_temp1 = lst_temp2[0].split(" ")
                    lst_temp2 = lst_temp1[1].split("x")
                    size = int(lst_temp2[1], 16)
                    find_label = None
                    return str(size)

if __name__ == '__main__':

    args = sys.argv[1:]
    file_name = args[0]

    if args[1] == "dtb":
        print(get_size(file_name, dtb_label))

    if args[1] == "kernel":
        print(get_size(file_name, kernel_label))

    if args[1] == "rootfs":
        print(get_size(file_name, rootfs_label))

